### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by eserte** [worthmine/Text-vCard-Precisely#2]
On my smoker systems I see mixed results, passes and fails. Failed test logs look like this:
```
#   Failed test 'photo(raw)'
#   at t/V3/image.t line 98.
#          got: 'BEGIN:VCARD
# VERSION:3.0
# PHOTO;ENCODING=b:iVBORw0KGgoAAAANSUhEUgAAAGQAAABkAQMAAABKLAcXAAAAA1BMVEUAA
#  ACnej3aAAAAFElEQVQ4jWNgGAWjYBSMglFATwAABXgAAfmlXscAAAAASUVORK5CYII=
# LOGO;ENCODING=b:iVBORw0KGgoAAAANSUhEUgAAAGQAAABkAQMAAABKLAcXAAAAA1BMVEUAAA
#  Cnej3aAAAAFElEQVQ4jWNgGAWjYBSMglFATwAABXgAAfmlXscAAAAASUVORK5CYII=
# END:VCARD
# '
#     expected: 'BEGIN:VCARD
# VERSION:3.0
# PHOTO;ENCODING=b:iVBORw0KGgoAAAANSUhEUgAAAGQAAABkAQMAAABKLAcXAAAAA1BMVEUAA
#  ACnej3aAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAFElEQVQ4jWNgGAWjYBSMglFATwAABXgAAfm
#  lXscAAAAASUVORK5CYII=
# LOGO;ENCODING=b:iVBORw0KGgoAAAANSUhEUgAAAGQAAABkAQMAAABKLAcXAAAAA1BMVEUAAA
#  Cnej3aAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAFElEQVQ4jWNgGAWjYBSMglFATwAABXgAAfml
#  XscAAAAASUVORK5CYII=
# END:VCARD
# '
(etc)
```

I don't see a pattern for the failures regarding operating systems or perl versions.

**Comment by worthmine** [comment]
thanks! I will see my source!

**Comment by worthmine** [comment]
Tests for photo(raw) may depend on your system.
Travis CI does skip this tests because it can't install GD.pm

Please tell me your perl version and OS.
My environment is perl 5.18, Mac OSX Sierra 10.12.6 and GD.pm 2.66

**Comment by eserte** [comment]
> Please tell me your perl version and OS.
My environment is perl 5.18, Mac OSX Sierra 10.12.6 and GD.pm 2.66

My observations are:
* it passes on FreeBSD 9.2 and 10.3
* it passes on Mac OSX El Capitan
* it passes on Ubuntu 16.04
* it fails on Debian 8 and 9 (but only if GD.pm is installed, it seems)

Perl version is irrelevant; I run my tests with many perl versions between 5.8.1 and 5.27.2.

Maybe the system gd's version is irrelevant? The Mac has 2.1.1 and 2.2.3 installed, not sure what's used for GD.pm. The FreeBSD boxes have 2.1.0 and 2.2.3. Ubuntu 16.04 has 2.1.1. Debian 8 has 2.1.0. Debian 9 has 2.2.4. So unfortunately still no clear result, with 2.1.0 there could be either passes (FreeBSD 9) or fails (Debian 8).

> Travis CI does skip this tests because it can't install GD.pm

Adding something like
```
sudo apt-get install -qq libgd2-xpm-dev
```
to the `before_install` section might help, resp. using `addons.apt.packages` if you have `sudo:false` configured.

**Comment by eserte** [comment]
I checked on Ubuntu12.04 (precise) and Ubuntu14.04 (trusty): it seems that it passes on 14.04 and fails on 12.04. So for travis-ci, you should probably add a configuration `dist: precise`, together with the installed libgd2 package it should be possible to reproduce the errors.

**Comment by worthmine** [comment]
I could see the error you said. however, what should I do next?

the strings encoded by base64 on test 6-7 int/V[3|4]/image.t are different.
So, it seems that  the raw image(png) binary made by GD may be different.

Is this still  the matter of this module?  or should I make always skip these tests?

**Comment by worthmine** [comment]
If it is the matter of my test scripts, Please show me the way.

**Comment by eserte** [comment]
My suggestion: emit a success if any of the both expected outputs matches. E.g. like this (untested pseudo code):
```
use List::Util 'first';
my @expect = ($expected_blob_1, $expected_blob_2);
if (first { $got eq $_ } @expect)
    pass "expected output";
} else {
    is $got, $expect[0]; # will fail, do it with is(), so we have $got & $expect printed out for diagnostics
}
```

**Comment by worthmine** [comment]
Thank you for teaching. I will try it.

**Comment by worthmine** [comment]
I did it!  #3(already merged) will help your tests.

If there are any issues around image.t, please continue.

**Comment by worthmine** [comment]
@eserte 
According to [cpantesters](http://www.cpantesters.org/distro/T/Text-vCard-Precisely.html), it seems that the strings encoded by base64(Espacialy from raw JPEG) depend on each environments.
So I can't avoid every FAILs with this way you taught me.

In this case, should I try to make sure tests with using `like` and regexp for base64?
Or may I use `skip` or `pass`?

**Comment by eserte** [comment]
First the analysis --- I see a pattern in the fails: on freebsd 9.2, freebsd 10.3, debian/wheezy and Ubuntu 16.04 it passes; whereas on CentOS6, debian/jessie and debian/stretch it fails. If I remember correctly there are two different jpeg libraries available in the open source world (jpeg-turbo and the IJG JPEG library), maybe  producing slightly different bit patterns.

 A diff in the V3/image.t fail (debian/stretch) shows the following:
```
@@ -5,7 +5,7 @@
 #  nej3aAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAFElEQVQ4jWNgGAWjYBSMglFATwAABXgAAfmlX
 #  scAAAAASUVORK5CYII=
 # PHOTO;TYPE=image/jpeg;ENCODING=b:/9j/4AAQSkZJRgABAQEAYABgAAD//gA
-#  +Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2NjIpLCBkZWZhdWx0IHF1Y
+#  +Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2OTApLCBkZWZhdWx0IHF1Y
 #  WxpdHkK/
 #  9sAQwAIBgYHBgUIBwcHCQkICgwUDQwLCwwZEhMPFB0aHx4dGhwcICQuJyAiLCMcHCg3KSwwMTQ
 #  0NB8nOT04MjwuMzQy/
```
So if the difference is indeed that small then it would be possible to normalize the output before doing the comparisons. Something like `$got =~ s/\Q+Q1JFQ.../+Q1JFQ.../`;

Another way is to continue with the already used technique, but you'll need even more samples in the t/{V3,V4}/Image directory...

**Comment by worthmine** [comment]
Thank you for teaching!

I will start from taking some diffs.

**Comment by worthmine** [comment]
It seems there are some variant at least 3 on JPEG and at least 2 on PNG.

I did the test on my vps(centOS) and passed with version 0.09.
Now I wait for [the tests](http://www.cpantesters.org/distro/T/Text-vCard-Precisely.html) on other environments.

If it fail, I will give up trying to fix the tests. Because, Actually, to be able to import some raw binary image is not the heart, just only a feature on this module.

I think the correctness of strings encoded by Base64 doesn't matter in this case. 

Thank you for everything.

**Comment by eserte** [comment]
0.09 looks quite good. No errors so far at CPAN Testers http://matrix.cpantesters.org/?dist=Text-vCard-Precisely+0.09 and no problems on my smokers.

Closing issue.

**Comment by worthmine** [comment]
Thanks agiain!
