### ISSUE TITLE
GD->new( ... some param ... )->plot()->png();

### ISSUE THREAD

**Issue by szabgab** [worthmine/Text-vCard-Precisely#21]
In the synopsis there is a code snipped

```
GD->new( ... some param ... )->plot()->png();
```

It would be nicer if the "some param" was replace by something that could work out of the box. (or out of the copy-paste)

**Comment by worthmine** [comment]
Thank you for suggesting!
I'll try that after fixing #20

**Comment by worthmine** [comment]
probably I did what you said.

You mean that synopsis should be a code that can run when pasted, don't you?

**Comment by szabgab** [comment]
I am not 100% sure in this, but I think that having a copy-paste-able synopsis would be a good idea.

I opened a discussion about this. You might be interested to read the opinion of others as well.
https://www.reddit.com/r/perl/comments/jbht86/should_the_synopsis_include_working_code_or_is/

**Comment by worthmine** [comment]
I really appreciate that you made a topic in reddit.

And every opinion in there is interesting.

thank you everything
