### ISSUE TITLE
Valid phone number not accepted

### ISSUE THREAD

**Issue by abraxxa** [worthmine/Text-vCard-Precisely#5]
The valid format is +12 345 6789 0123 which is one digit longer than what is currently accepted by your module.

**Comment by worthmine** [comment]
thank you for reporting.
I have fixed it so please check it.

The next release will be after that #6 is fixed.

**Comment by worthmine** [comment]
@abraxxa , May I close this issue?

**Comment by abraxxa** [comment]
Sorry for the late reply.
I've checked version 0.17 but some valid phone number are still not accepted.
The country code may be three digits long: https://en.wikipedia.org/wiki/Telephone_numbers_in_Slovakia

And the phone number might be longer as well. Maybe you shouldn't validate them so strictly at all of use a module that does this well as it's quite complex.

**Comment by worthmine** [comment]
I agree with you.

**Comment by worthmine** [comment]
On version 0.18, I give up to validate phone numbers
