### ISSUE TITLE
as_file is missing _path and _iomode_out methods

### ISSUE THREAD

**Issue by abraxxa** [worthmine/Text-vCard-Precisely#6]
Both V3 and V4.

**Comment by worthmine** [comment]
Thank you for notifying and I'm sorry that there is something missing.

 I found there is no test for as_file(). 

I will fix it. so give me a few days.

**Comment by worthmine** [comment]
Now we have a correct method as_file().
 
https://github.com/worthmine/Text-vCard-Precisely/releases/tag/0.14

**Comment by worthmine** [comment]
@abraxxa , May I close this issue?

**Comment by worthmine** [comment]
http://matrix.cpantesters.org/?dist=Text-vCard-Precisely+0.14

new test fail with win32. so I have to fix it.

**Comment by worthmine** [comment]
https://github.com/worthmine/Text-vCard-Precisely/releases/tag/0.16

I have fixed the Issue. @abraxxa , now you can try it.

**Comment by abraxxa** [comment]
Thanks but I'm writing the file myself as I put multiple vcards into a single file.

**Comment by worthmine** [comment]
ah, multiple vCards into a single files is a new TO DO.

**Comment by worthmine** [comment]
@abraxxa , I have improved  this Module for operating Multiple vCards on single file. #11 
But it may have some bugs. Please try it so carefully.

**Comment by worthmine** [comment]
the document is here https://metacpan.org/pod/Text::vCard::Precisely::Multiple
